# application.yml

# Application information
application:
  name: mongo-templates
  description: "Mongo best practices in the form of template examples"
  version: 1.0.0
  contact:
    name: "Ryan Gross"
    email: "ryangros47@gmail.com"


# MongoDB Configuration (development profile)
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: example
      username: user
      password: password
      authentication-database: admin

# MongoDB Configuration (production profile)
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: prod.mongodb.net
      port: 27017
      database: production
      username: user
      password: password
      authentication-database: admin
