services:
  mongo:
    image: mongo:latest
    container_name: mongo-replset
    command: ["mongod", "-f", "etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
      - ./logs/:/var/log/mongodb/
      - ./config/mongoConfigs/mongod.conf:/etc/mongod.conf
      - ./config/mongoInit.js:/docker-entrypoint-initdb.d/mongoInit.js
volumes:
  mongo-volume:

