services:
  mongo:
    image: mongo:latest
    container_name: mongo-replset
    command: ["mongod", "-f", "etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
      - ./logs/:/var/log/mongodb/
      - ./config/mongoConfigs/primaryMongod.conf:/etc/mongod.conf
      - ./config/mongoInit.js:/docker-entrypoint-initdb.d/mongoInit.js
    networks:
      - mongo-network

  mongo-secondary1:
        image: mongo:latest
        container_name: mongo-secondary1
        command: ["mongod", "-f", "etc/mongod.conf"]
        volumes:
          - mongo-secondary1-data:/data/db
          - ./config/mongoConfigs/secondaryOne.conf:/etc/mongod.conf
          - ./logs/secondaryOne/:/var/log/mongodb/
        networks:
          - mongo-network

  mongo-secondary2:
        image: mongo:latest
        container_name: mongo-secondary2
        command: ["mongod", "-f", "etc/mongod.conf"]
        volumes:
          - mongo-secondary2-data:/data/db
          - ./config/mongoConfigs/secondaryTwo.conf:/etc/mongod.conf
          - ./logs/secondaryTwo/:/var/log/mongodb/
        networks:
          - mongo-network

volumes:
  mongo-primary-data:
  mongo-secondary1-data:
  mongo-secondary2-data:

networks:
  mongo-network:

