services:
  mongo:
    image: mongo:latest
    container_name: mongo-replset
    command: ["mongod", "-f", "etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
      - ./logs/:/var/log/mongodb/
      - ./mongod.conf:/etc/mongod.conf
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-volume:

