services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    hostname: mongo-primary
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
      # - ./logs/:/var/log/mongodb/ logging
      - ./config/mongoConfigs/primary.conf:/etc/mongod.conf
      - ./config/users:/users
    networks:
      - mongo-network
    healthcheck:
      test: echo "rs.status()"
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30


  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    hostname: mongo-secondary1
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    ports:
      - "27018:27017"
    volumes:
      - mongo-secondary1-data:/data/db
      - ./config/mongoConfigs/secondary.conf:/etc/mongod.conf
      - ./config/users:/users
    networks:
      - mongo-network

  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    hostname: mongo-secondary2
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    extra_hosts:
      - "mongo-secondary2:127.0.0.1"
    ports:
      - "27019:27017"
    volumes:
      - mongo-secondary2-data:/data/db
      - ./config/mongoConfigs/secondary.conf:/etc/mongod.conf
      - ./config/users:/users
    networks:
      - mongo-network

volumes:
  mongo-primary-data:
  mongo-secondary1-data:
  mongo-secondary2-data:

networks:
  mongo-network:
    driver: bridge