services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    hostname: mongo-primary
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    volumes:
      - mongo-primary-data:/data/db
      - ./logs/:/var/log/mongodb/
      - ./config/mongoConfigs/primary.conf:/etc/mongod.conf
      #- ./config/initialize_replica_set.sh:/docker-entrypoint-initdb.d/initialize_replica_set.sh
    networks:
      - mongo-network
    healthcheck:
      test: |
        echo "try { rs.status() } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [
              { _id: 0, host: 'host.docker.internal:27017', priority: 1 },
              { _id: 1, host: 'host.docker.internal:27018', priority: 0.5 },
              { _id: 2, host: 'host.docker.internal:27019', priority: 0.5 }
            ]
          })
        }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
  

  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    hostname: mongo-secondary1
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27018:27017"
    volumes:
      - mongo-secondary1-data:/data/db
      - ./config/mongoConfigs/secondary.conf:/etc/mongod.conf
      - ./logs/secondaryOne/:/var/log/mongodb/
    networks:
      - mongo-network

  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    hostname: mongo-secondary2
    command: ["mongod" , "-f", "/etc/mongod.conf"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27019:27017"
    volumes:
      - mongo-secondary2-data:/data/db
      - ./config/mongoConfigs/secondary.conf:/etc/mongod.conf
      - ./logs/secondaryTwo/:/var/log/mongodb/
    networks:
      - mongo-network

volumes:
  mongo-primary-data:
  mongo-secondary1-data:
  mongo-secondary2-data:

networks:
  mongo-network:
